name: Build and Deploy to Firebase

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Use the production environment

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Docker build environment
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build the Docker image
      - name: Build Docker Image
        run: |
          docker build --build-arg GITHUB_ACTIONS=true -t my-app .

      # Run the Docker container to deploy
      - name: Run Docker Container to Deploy
        run: |
          docker run --rm -e FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }} my-app

