name: Deploy to Firebase

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # Use the production environment

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Install Firebase tools globally in the GitHub Actions environment
      - name: Install Firebase CLI
        run: |
          npm install -g firebase-tools

      # Build the Docker image and deploy using Firebase
      - name: Build and Deploy with Docker
        run: |
          # Build the Docker image, passing the GITHUB_ACTIONS variable
          docker build --build-arg GITHUB_ACTIONS=true -t my-app .
          
          # Run the Docker container, passing the Firebase token and running npm run build
          docker run --rm -e FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }} my-app npm run build

      # Deploy to Firebase using the Firebase CLI in the GitHub Actions environment
      - name: Deploy to Firebase
        run: |
          firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
